# Generated by Django 5.2.3 on 2025-06-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='tasks',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
